# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: impala.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cimpala.proto\x12\x06impala\"\x07\n\x05\x45mpty\"%\n\x10\x43onnectionStatus\x12\x11\n\tconnected\x18\x01 \x01(\x08\"\x17\n\x05State\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\x17\n\x06\x41\x63tion\x12\r\n\x05value\x18\x01 \x01(\x01\"\x1b\n\nActionProb\x12\r\n\x05probs\x18\x01 \x03(\x01\"\x17\n\x06Reward\x12\r\n\x05value\x18\x01 \x01(\x01\"\x15\n\x04\x44one\x12\r\n\x05value\x18\x01 \x01(\x08\"\xf0\x01\n\x0e\x45xperienceData\x12\x1c\n\x05state\x18\x01 \x03(\x0b\x32\r.impala.State\x12\x1e\n\x06\x61\x63tion\x18\x02 \x03(\x0b\x32\x0e.impala.Action\x12\'\n\x0b\x61\x63tion_prob\x18\x03 \x03(\x0b\x32\x12.impala.ActionProb\x12\x1e\n\x06reward\x18\x04 \x03(\x0b\x32\x0e.impala.Reward\x12\x1a\n\x04\x64one\x18\x05 \x03(\x0b\x32\x0c.impala.Done\x12!\n\nnext_state\x18\x06 \x03(\x0b\x32\r.impala.State\x12\x18\n\x10\x65xperience_count\x18\x07 \x01(\x05\"`\n\x11\x45xperienceRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12*\n\nexperience\x18\x02 \x01(\x0b\x32\x16.impala.ExperienceData\x12\x10\n\x08\x61\x63tor_id\x18\x03 \x01(\x05\"&\n\x11ParameterResponse\x12\x11\n\tparameter\x18\x01 \x01(\x0c\x32\xcb\x01\n\rImpalaService\x12<\n\x0f\x43heckConnection\x12\r.impala.Empty\x1a\x18.impala.ConnectionStatus\"\x00\x12<\n\x0eSendExperience\x12\x19.impala.ExperienceRequest\x1a\r.impala.Empty\"\x00\x12>\n\x10RequestParameter\x12\r.impala.Empty\x1a\x19.impala.ParameterResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'impala_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=24
  _globals['_EMPTY']._serialized_end=31
  _globals['_CONNECTIONSTATUS']._serialized_start=33
  _globals['_CONNECTIONSTATUS']._serialized_end=70
  _globals['_STATE']._serialized_start=72
  _globals['_STATE']._serialized_end=95
  _globals['_ACTION']._serialized_start=97
  _globals['_ACTION']._serialized_end=120
  _globals['_ACTIONPROB']._serialized_start=122
  _globals['_ACTIONPROB']._serialized_end=149
  _globals['_REWARD']._serialized_start=151
  _globals['_REWARD']._serialized_end=174
  _globals['_DONE']._serialized_start=176
  _globals['_DONE']._serialized_end=197
  _globals['_EXPERIENCEDATA']._serialized_start=200
  _globals['_EXPERIENCEDATA']._serialized_end=440
  _globals['_EXPERIENCEREQUEST']._serialized_start=442
  _globals['_EXPERIENCEREQUEST']._serialized_end=538
  _globals['_PARAMETERRESPONSE']._serialized_start=540
  _globals['_PARAMETERRESPONSE']._serialized_end=578
  _globals['_IMPALASERVICE']._serialized_start=581
  _globals['_IMPALASERVICE']._serialized_end=784
# @@protoc_insertion_point(module_scope)
